Robustness: Translate tab characters in SUBJECT to spaces
miniDB does not support tab characters in the key, but the fact that we're using that for persistence should remain hidden to users. Therefore, translate tab characters to spaces to avoid the error.
> ERROR: KEY cannot contain tab characters.